# Generated by Django 4.2.7 on 2024-03-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sphmmcApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30)),
                ('email_password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FbUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_username', models.CharField(max_length=30)),
                ('fb_password', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Applicant',
        ),
    ]
