# Generated by Django 4.2.7 on 2024-03-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sphmmcApp', '0002_emailuser_fbuser_delete_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbuser',
            name='session_key',
            field=models.CharField(default='1', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fbuser',
            name='trial_session',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
