# Generated by Django 4.2.7 on 2024-03-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sphmmcApp', '0004_rename_trial_session_fbuser_trial_per_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbuser',
            name='session_key',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
