# Generated by Django 4.2.7 on 2024-03-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sphmmcApp', '0005_alter_fbuser_session_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=300)),
                ('lname', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('fieldOfInterest', models.CharField(choices=[('Nurse', 'Nurse'), ('Anesthesia Specialist', 'Anesthesia Specialist'), ('Health Officer', 'Health Officer')], max_length=300)),
            ],
        ),
    ]
