# Generated by Django 4.2.7 on 2024-03-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sphmmcApp', '0006_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone2',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
