# Generated by Django 4.2.7 on 2024-03-20 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sphmmcApp', '0007_account_phone2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='fieldOfInterest',
            new_name='field_of_interest',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='lname',
            new_name='last_lname',
        ),
    ]
