# Generated by Django 4.2.7 on 2024-03-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sphmmcApp', '0011_alter_account_email_alter_account_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone2',
            field=models.CharField(max_length=300),
        ),
    ]
