# Generated by Django 4.2.7 on 2024-03-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sphmmcApp', '0012_alter_account_email_alter_account_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailuser',
            name='session_key',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='emailuser',
            name='trial_per_session',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
